### ISSUE TITLE
docker container support

### ISSUE THREAD

**Issue by coldbrew1420** [Borvik/vscode-postgres#123]
I'm attempting to connect with my cluster which is hosted on a docker container and I get the following error.

```
no pg_hba.conf entry for host "xxx.xx.x.x", user "postgres", database "postgres", SSL off
```

Note: the pg_hba.conf file is within a data directory that is mounted in the container. On my machine, it is a non-standard directory which is mounted to /var/lib/postgresql/data within the container. I am using docker-hub's [postgres image](https://hub.docker.com/_/postgres)

**Comment by CharlesHolbrow** [comment]
I've been using this vs-code extension with a docker Postgres server, and it's working fine for me. Are you sure that have the appropriate ports open, and are connecting with the correct user/password?

**Comment by arielbotti** [comment]
Hello there. I had the same issue today and I didn't have the ports open. 

My docker compose file:

docker-compose.yml

```
version: "3.9"

services:
  db:
    image: postgres:15.2
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=put_here_user
      - POSTGRES_PASSWORD=put_here_pass
    ports:
      - "5432:5432"  
```
